FROM arm32v7/python:3.7-slim-buster

RUN apt-get update
RUN apt-get -y install gcc

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]